In [3]:
from __future__ import print_function

In [4]:
import torch

In [5]:
torch.__version__

'1.2.0+cpu'

In [6]:
x = [1,2,3,4,5,6]

In [8]:
torch.is_tensor(x)

False

In [9]:
torch.is_storage(x)

False

In [10]:
y = torch.randn(1,2,3,4,5)

In [11]:
torch.is_tensor(y)

True

In [12]:
torch.is_storage(y)

False

In [13]:
torch.numel(y)

120

In [16]:
y

tensor([[[[[ 1.5970,  2.7420, -0.4462, -1.0228,  0.1337],
           [-2.2170,  0.0476,  0.3446, -0.4929,  0.4277],
           [-2.2580,  0.7490,  1.4926,  0.2630, -0.2205],
           [-0.0329, -1.2149,  0.1800,  1.0960, -1.2096]],

          [[-0.5975,  0.9818,  1.0975,  0.6137,  0.2796],
           [-0.8606, -0.1530,  0.7007,  0.6510,  0.0978],
           [-1.5186,  1.5567, -1.4652, -0.7815, -0.3657],
           [ 0.4738,  1.5154, -0.5178,  0.6860, -0.7923]],

          [[ 0.6204,  0.1087,  0.1421, -0.0982,  0.2573],
           [-1.3661,  0.1163, -1.8164,  0.7040,  0.7200],
           [-1.3590,  1.3230,  0.0571,  0.4780,  1.1363],
           [ 0.7148,  0.4734, -0.0137,  0.2822,  0.7259]]],


         [[[-0.1817,  2.7355, -0.0544, -1.3709,  1.0294],
           [ 0.8182, -0.1201, -1.5445, -1.0805,  1.1204],
           [-0.1210, -0.0721, -0.1627, -0.1856, -0.5178],
           [-0.5882, -0.3944, -0.9124,  1.4965, -0.7811]],

          [[ 0.0342,  0.3377,  0.6607, -1.1904,  0.2515],
    

In [15]:
y.shape

torch.Size([1, 2, 3, 4, 5])

In [17]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
torch.numel(torch.zeros(4,4))

16

In [19]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [20]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [21]:
import numpy as np
x1 = np.array(x)

In [23]:
x1

array([1, 2, 3, 4, 5, 6])

In [26]:
torch.from_numpy(x1)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.int32)

In [29]:
torch.linspace(2,10, steps=25)

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [30]:
torch.logspace(2,10, steps=25)

tensor([1.0000e+02, 2.1544e+02, 4.6416e+02, 1.0000e+03, 2.1544e+03, 4.6416e+03,
        1.0000e+04, 2.1544e+04, 4.6416e+04, 1.0000e+05, 2.1544e+05, 4.6416e+05,
        1.0000e+06, 2.1544e+06, 4.6416e+06, 1.0000e+07, 2.1544e+07, 4.6416e+07,
        1.0000e+08, 2.1544e+08, 4.6416e+08, 1.0000e+09, 2.1544e+09, 4.6416e+09,
        1.0000e+10])

In [31]:
torch.rand(10)

tensor([0.9219, 0.5042, 0.3502, 0.2915, 0.4476, 0.2773, 0.3538, 0.7439, 0.2121,
        0.3536])

In [33]:
torch.rand(10, 10).shape

torch.Size([10, 10])

In [34]:
torch.randn(10, 10).shape

torch.Size([10, 10])