In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
x = Variable(torch.ones(5,5))
linear = nn.Linear(5,1)
y = linear(x)

In [3]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [4]:
y

tensor([[-0.0660],
        [-0.0660],
        [-0.0660],
        [-0.0660],
        [-0.0660]], grad_fn=<AddmmBackward>)

In [8]:
class AddNoise(torch.nn.Module):
    def __init__(self, mean=0.0, stddev=0.1):
        super(AddNoise, self).__init__()
        self.mean = mean
        self.stddev = stddev
        
    def forward(self, input):
        noise = input.clone().normal_(self.mean, self.stddev)
        return input + noise
    
noisificator = AddNoise()
print(noisificator(x))

tensor([[1.0599, 1.0262, 1.2393, 0.9733, 1.2481],
        [0.8107, 1.0075, 0.9304, 1.0571, 1.0623],
        [1.0265, 1.1115, 0.9861, 1.1159, 0.8529],
        [1.1732, 1.0114, 0.8022, 1.2192, 0.8534],
        [1.1620, 1.0535, 1.0107, 0.9394, 1.1440]])


In [15]:
torch.rand(1, 1, 32, 32).shape

torch.Size([1, 1, 32, 32])

In [16]:
torch.rand(32, 32).shape

torch.Size([32, 32])

In [17]:
torch.rand(1, 32, 32).shape

torch.Size([1, 32, 32])

In [18]:
model = nn.Sequential(
    nn.Conv2d(1, 20, 5),
    nn.ReLU(),
    nn.Conv2d(20, 64, 5),
    nn.ReLU())

image = Variable(torch.rand(1, 1, 32, 32))
model(image).shape

torch.Size([1, 64, 24, 24])

In [20]:
x = Variable(torch.randn(10,3))
y = Variable(torch.ones(10).type(torch.LongTensor))
w = Variable(torch.Tensor([0.2, 0.2, 0.6]))
loss_f = torch.nn.CrossEntropyLoss(weight=w)
loss_v = loss_f(x, y)